/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void googleTest() throws InterruptedException {
        var options = new FirefoxOptions();
        options.addArguments("--safe-mode");
        var browser = new FirefoxDriver(options);

        browser.get("https://www.google.com");
        Thread.sleep(5000);
        browser.close();
    }
}
