/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;

class AppTest {
    WebDriver browser;

    @BeforeEach
    void beforeEach() {
        var options = new FirefoxOptions();
        options.addArguments("--safe-mode");
        options.setCapability("webSocketUrl", true);
        browser = new FirefoxDriver(options);
    }

    @Test
    void googleTest() throws InterruptedException {
        browser.get("https://www.google.com");
        Thread.sleep(5000);

        // Check if the title contains "Google" - ADD
        var googleSearchBox = browser.findElement(By.name("q"));
        googleSearchBox.sendKeys("iphone");
        Thread.sleep(2000);
    }

    @AfterEach
    void afterEach() {
        browser.close();
    }
}
